name: dji_waypoint_engine
description: A package to generate DJI Waypoint Missions compatible with DJI Fly and DJI Pilot
version: 0.0.1

environment:
  sdk: "^3.0.0"

dependencies:
  archive: ^3.6.1
  xml: ^6.5.0
dev_dependencies:
  test: ^1.25.8
